### ISSUE TITLE
How to use Multiple DbContexts ?

### ISSUE THREAD

**Issue by houssam-saissi** [skoruba/IdentityServer4.Admin#100]
Hi @skoruba ,

How  to use Multiple DbContexts with multiple Databases ?  I want to use : 
- 1 database for Clients, ApiScopes, ApiResources, PersistedGrants ...
- 1 database for Users, Roles, UserClaims ...

I have created a new DbContext (AuthDbContext) but i'm confused how to get it work :/ 

Any idea ? ^_^

**Comment by skoruba** [comment]
Hi @houssam-saissi 
Great question, I will try this use case and I will send some example for you.

Thanks!

**Comment by skoruba** [comment]
Hi @houssam-saissi,

Sorry for the delay. Currently you need to consider if you want to show the userName and some other information about user in view c
alled PersistedGrants, because this view is bound with Asp.Net Core Identity. Or you can use Services/Repositories of PersistedGrants without relationship to Asp.Net Core Identity and show for example only SubjectId which is part of PersistedGrant table.
Please let me know.
Thanks.
Jan

**Comment by skoruba** [comment]
Done on `master`. Please check new release.
Thanks!
