### ISSUE TITLE
Login button doesn't work on Internet Explorer

### ISSUE THREAD

**Issue by Hens94** [skoruba/IdentityServer4.Admin#113]
When I try to login on Login view using internet explorer, the login button doesn't work. I tried with other browser and this issue doesn't happen

Regards

**Comment by skoruba** [comment]
Hey, 
I will check it, thanks!

**Comment by drasalskis** [comment]
Problem is not Login button, but always invalid login form when checking for required fields (Username and Password), because of bug in jquery-validation plugin 1.18.0. 

Upgrade jquery-validation plugin to v1.19.0 to solve this issue. 

More info here: 
https://github.com/jquery-validation/jquery-validation/issues/2211

**Comment by skoruba** [comment]
Thanks, I will update it!

**Comment by skoruba** [comment]
@drasalskis - You are right, I've updated jquery-validation and now it's working great. Thank you!
