### ISSUE TITLE
Add profile management into STS

### ISSUE THREAD

**Issue by skoruba** [skoruba/IdentityServer4.Admin#149]
We can use Scaffold Identity:
- https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio

Or use MVC version
- https://github.com/damienbod/IdentityServer4AspNetCoreIdentityTemplate

**Comment by duki994** [comment]
@skoruba 

Just a quick heads-up.
There is a little issue on scaffolder.

All projects must use C# 7.0 or less to be able to run scaffolder.
Then can be switched to C# 7.0+.

Can be problem if default literal was used throught project (haven't noticed it).


I will see to integrate it and send a PR request in free time since I already have something like that in an older project (but it's upgraded to IS4 2.3 and .NET Core 2.2) :)

**Comment by skoruba** [comment]
@duki994 - Please, take a look at this PR: https://github.com/skoruba/IdentityServer4.Admin/pull/161
- We are working on it. :)
Thank you.

**Comment by skoruba** [comment]
Done on `master`.
