### ISSUE TITLE
Make it easier to extend

### ISSUE THREAD

**Issue by aiscrim** [skoruba/IdentityServer4.Admin#203]
Currently the library relies on a set of repositories that are not easy to extend: the repository classes don't have virtual methods and they have private members instead of protected ones, and some data come from public static classes like ClientConst. 
That makes it very difficult to extend the functionalities: for example, I wanted to add SAML 2.0 to the supported Protocol Types in my application, and I had to implement again IClientRepository, copying the whole implementation of ClientRepository and replacing just the GetProtocolTypes() method with one that instead of calling the static ClientConsts.GetProtocolTypes() returns the two protocol types I need.

**Comment by skoruba** [comment]
@aiscrim - Good point, I agree with you - I will change it.
Thank you 👍

**Comment by skoruba** [comment]
@aiscrim - Done on `dev` branch.
Thanks

**Comment by CoskunSunali** [comment]
The same goes for using custom data stores. You expect the custom AdminDbContext to inherit from IdentityDbContext but why? Even Asp.Net Core Identity supports custom data stores that doesn’t inherit from that base class. Identity Server 4 doesn’t have such requirement either. Would you consider implementing ability to support custom data stores instead of requiring to have it inherit from IdentityDbContext?

**Comment by skoruba** [comment]
@CoskunSunali - Thank you for your suggestion, you are right, we have already done this issue. :)

**Comment by CoskunSunali** [comment]
@skoruba Great work, thanks!

**Comment by skoruba** [comment]
Done on `master`. Please check new release.
Thanks!
