### ISSUE TITLE
Log details

### ISSUE THREAD

**Issue by xmichaelx** [skoruba/IdentityServer4.Admin#221]
![obraz](https://user-images.githubusercontent.com/1004852/54268707-1f9aa300-457c-11e9-832e-df2302f7bbbe.png)

Clicking on ShowDetails does not show any detail info (it is available in the database).

**Comment by skoruba** [comment]
It is probable bug or incorrect configuration in MsSql Sink for Serilog, because in configuration is defined the additional column for detail error message and it doesn’t work (stored only default xml version of error message, not json). I will try to switch back to configuration in source code, but it is not so flexible like from appsettings.json.
Thanks for reporting. ;)

**Comment by skoruba** [comment]
It is necessary to upgrade package: `Serilog.Sinks.MSSqlServer` to `5.1.3-dev-00232`.

**Comment by skoruba** [comment]
Done on master.
Thanks
