### ISSUE TITLE
Add custom validation for new fields on User

### ISSUE THREAD

**Issue by pbros** [skoruba/IdentityServer4.Admin#238]
Hello,

I added a new field on my Identity User class, and I want add some new validation on this field. (e.g. validate that specified value exists in another database)

From what I can tell, the only place I could add it in my Admin Website would be in `BaseIdentityController`
```csharp
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> UserProfile(TUserDto user)
{}
```

I usually prefer not having business logic in my controllers, so I was wondering if there was another way to achieve this.

Thanks

**Comment by pbros** [comment]
It looks like I might be able to implement a custom validator using FluentValidation.

https://fluentvalidation.net/aspnet#asp-net-core

With something like

```csharp
services.AddTransient<IValidator<UserIdentity>, UserIdentityValidator>();
```

Will update after testing

**Comment by pbros** [comment]
It turns out I had to create the validator on the DTO. Still not 100% ideal since I would have liked to add the validation on the base type, but at least this works.

For reference
```csharp
public class UserDtoValidator : AbstractValidator<UserDto<string>>
{
    public UserDtoValidator()
    {
        RuleFor(x => x.CustomDecimalField).GreaterThanOrEqualTo(0);
    }
}
```
In `StartupHelpers.cs`
```csharp
services.AddMvc().AddFluentValidation()
//...
services.AddTransient<IValidator<UserDto<string>>, UserDtoValidator
```

Does anybody know of a way to add the validation directly on UserIdentity?

**Comment by skoruba** [comment]
Hi @pbros ,

Thank you for your info about using of `FluentValidation`.

I would suggest to create your own implementation of `IdentityService` - ideally from `dev` branch because we improved the inheritents.

If you want to validate the `UserIdentity` - you can register this object via `FluentValidation` but you need create this validation manually - for example in `IdentityService`.

BTW: I think validation of DTO is better from my point of view.

Give me please some feedback about your final solution. :-)

**Comment by pbros** [comment]
I'll stick to the DTO for now, as it will be simpler to maintain. I will re-open if I decide to go another way.

Thanks!
