### ISSUE TITLE
Database configuration

### ISSUE THREAD

**Issue by marcomaq** [skoruba/IdentityServer4.Admin#239]
Hi, 

I download the master version, beacasue I want to test the project with a MS SqlServer instance. 

I change this lines in the appsettings.json

From; 

>    // "AdminConnection": "Server=(localdb)\\mssqllocaldb;Database=IdentityServer4Admin;Trusted_Connection=True;MultipleActiveResultSets=true"

To this; 

>     "AdminConnection": "Data Source=(LocalDb)\\MSSQLLocalDB;database=IdentityServer4Admin;trusted_connection=yes"

I am getting this error page; 

> An unhandled exception occurred while processing the request.
> Win32Exception: Unknown error (0x89c5010a)
> Unknown location
> 
> SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 50 - Local Database Runtime error occurred. Error occurred during LocalDB instance startup: SQL Server process failed to start.

Can some one tell me if where is the issue?

**Comment by TomasHubelbauer** [comment]
Can you try and see if `sqllocaldb info` lists the expected databases for the same user?

https://stackoverflow.com/a/36157192/2715716

The issue you are describing here is a connectivity one, IS4A or any other projects rely on the connection string being correct as well as the DB server running, so as long as your SQL Server Management Studio can connect with a given connection string, the app should be able to, too.

You may find that the DB is inaccessible because the LocalDB instance has not been created or you do not have LocalDB installed. It may also be stopped.

**Comment by skoruba** [comment]
I am closing it, feel free reopen it.
Thanks
