### ISSUE TITLE
Seed and Migration issues with PostgreSQL

### ISSUE THREAD

**Issue by brnbs** [skoruba/IdentityServer4.Admin#261]
We started experimenting with this project and followed the instructions in the PostgreSQL tutorial, but we ran into a few issues during migration and seed.

The first issue was a syntax error:
```
PM> Update-Database -context AdminIdentityDbContext
Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "["
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```
We replaced all [ and ] characters to double quotes in the migration scripts coming from the template, and it seems to solved the issue.

Later in the seed process we also got a nice exception:
```
dotnet run /seed

Unhandled Exception: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Npgsql.PostgresException: 23502: null value in column "Id" violates not-null constraint
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
```
We solved this by removing `filter: "[<column-name-here>] IS NOT NULL"` lines from migration scripts.

We also had to do a replace in all migration scripts from `.Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)` to `.Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)`

We are not sure if these were the best solutions to these exceptions but someone might find these information useful.

**Comment by alkubo** [comment]
Did you try to re-create the migrations using dotnet ef migrations add migrationname command after changing the database engine?

**Comment by deaktomi** [comment]
Okay, we believe we solved the issue. Something was not clear maybe because the lack of experience with migrations in .NET Core.

- After generating the project from the template:

```
dotnet new skoruba.is4admin --name MyProject --title MyProject --adminrole MyRole --adminclientid MyClientId --adminclientsecret MyClientSecret
```

- We updated the connection strings.
- Installed the NuGet packages for PostgreSQL
```
Npgsql.EntityFrameworkCore.PostgreSQL
Npgsql.EntityFrameworkCore.PostgreSQL.Design
```
- In `Helpers\StartupHelpers.cs` we found all usage of `UseSqlServer` and change to `UseNpgsql`.
- **Then when we ran the migration script we faced an error.**
```
Add-Migration AspNetIdentityDbInit -context AdminIdentityDbContext -output Data/Migrations/Identity
```
The error:
```
The name 'AspNetIdentityDbInit' is used by an existing migration.
```
- We thought that there won't be a problem since it is already generated (but not regenerated). Now we know it didn't update anything.
- Then running the Update-Database command failed
```
Update-Database -context AdminIdentityDbContext
```
The error:
```
Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "["
```
Of course it happened because the file `Data/Migration/Identity/AdminIdentityDbContextModelSnapshot.cs` contained code for MsSqlServer migration.

**What we had to do to REgenerate the migrations for the new database:**
Delete the content of the following folders:
- Data/Migration/Identity/
- Data/Migration/IdentityServerConfiguration/
- Data/Migration/IdentityServerGrants/
- Data/Migration/Logging

Please confirm us that we did the correct method. Also consider update the [readme](https://github.com/skoruba/IdentityServer4.Admin/blob/master/docs/EFMigration.md#postgresql). The "(re)generate migrations for new database" may be not clear enough that the files should be be deleted first.

**Comment by skoruba** [comment]
Sorry for delay - thanks for detailed explanation of your scenario. I think you are right - I will update docs - because the description it is not clear.
The re-generation of migration solves this issue.
Thanks!
