### ISSUE TITLE
Trying to add extra Properties to "UserIdentity" Object

### ISSUE THREAD

**Issue by bsheriff** [skoruba/IdentityServer4.Admin#308]
Hi,

During registration, I would like for the user to enter his/her first name and last name along with the other information (username, email address, etc.).  So what I did was first add FirstName and LastName properties to the "RegistrationViewModel".  The next thing I did is add the FirstName and LastName properties to the "UserIdentity" object (which inherits from the "IdentityUser" object).  Now in the "AccountController" in the "Register" action I try to create a new "TUser" object and assign the "FirstName" and "LastName" properties to that object.  It cannot find those properties.  The reason I add "FirstName" and "LastName" to the "UserIdentity" object is because I want to add those as columns to the "Users" table (not sure if this is bad practice or not, or should i just be adding firstname and lastname to the userclaims table).

The "AccountController" seems to be a generic Controller - "AccountController<TUser, TKey>" where the TUser : IdentityUser<TKey>.

How can I populate custom added properties such as "FirstName" and "LastName" in the TUser class from the "Register" action in the "AccountController"?

Is it wrong to add "FirstName" and "LastName" properties to the "UserIdentity" object (is it bad practice to add custom claims as columns of the Users table?

Should I just be adding any custom claims I want returned in the UserClaims table?

Thanks!

**Comment by skoruba** [comment]
Hi,
for this use case I can suggest add these information into claims:

Here I would add the method for adding new claims:
https://github.com/skoruba/IdentityServer4.Admin/blob/master/src/Skoruba.IdentityServer4.STS.Identity/Controllers/AccountController.cs#L565

```csharp
var identityResult = await _userManager.AddClaimsAsync(user, new List<Claim>
                {
                    new Claim(JwtClaimTypes.GivenName, model.GivenName),
                    new Claim(JwtClaimTypes.FamilyName, model.FamilyName),
                });
```
And extend `RegisterViewModel` with props - `GivenName` and `FamilyName`.

We add the additional user information into claims here (for user profile):
https://github.com/skoruba/IdentityServer4.Admin/blob/master/src/Skoruba.IdentityServer4.STS.Identity/Controllers/ManageController.cs#L648

This is easy way how to extend user profile with additional information without adding new column in database.

We use this approach because we want to use default db schema as much as possible and for additional information simply add new claims. I think both scenarios are valid. :)

**Comment by bsheriff** [comment]
Hi,

Thank you very much for the quick response.  It makes sense now, but I have just one question about your response.  When you say "We add additional user information into claims here (for user profile)", I am a little confused about what we are adding in this method (UpdateUserClaimsAsync) and where we are adding it to, and the purpose of adding to this method (Where is this method used).  Sorry about the questions, but I am a little new to identity server.

Thank you for the help!

**Comment by skoruba** [comment]
When we considered how to build profile view with additional user information - like website, full name and location - we decided to put these information into claims instead of create new columns in db. So if you check managecontroller and index view - these information are stored in claims. And method updateuserclaims - synchronize existing and new claims then store them into UserClaims.

**Comment by bsheriff** [comment]
Hi,

So I was able to save the "given_name" and "family_name" claims in the "UserClaims" table.  So, the issue I am having now is returning those values inside of the token that is returned.  I want to access the "given_name" and the "family_name" in my angular application.  Also, I would like to access the "email" claim as well.  Do I need to add extra logic somewhere to add this functionality?

Thanks

**Comment by skoruba** [comment]
If you need retrieve these new additional claims in tokens - you need define resource for it and then this scope ask in your client side.

**Comment by skoruba** [comment]
May I close it?
Thanks

**Comment by bsheriff** [comment]
Yes, you may close this.  Thank you very much for the help.  This is an amazing solution, it has helped me out immensely.

**Comment by skoruba** [comment]
If you will have any questions, let me know. :)
