### ISSUE TITLE
Execute multiple Projects (STS, Admin and API)

### ISSUE THREAD

**Issue by nk-cmd** [skoruba/IdentityServer4.Admin#554]
Hello,

Great respect for the work in your repo so far! 
I'm currently testing the repo and I noticed that you can't run the projects STS (IdentityServer), Admin and API at the same time. Apparently STS starts on the same port as the API? 

API
     "ApiBaseUrl": "http://localhost:5001",
     "IdentityServerBaseUrl": "http://localhost:5000",

Admin
    "IdentityAdminRedirectUri": "http://localhost:9000/signin-oidc",
    "IdentityServerBaseUrl": "http://localhost:5000",

STS
    "IdentityAdminBaseUrl": "http://localhost:9000",

I got always the error message
[11:51:48 FTL] Unable to start Kestrel.
System.IO.IOException: Failed to bind to address https://localhost:5001.

I tested the starting order of the projects is as follows:
STS
Admin
API

or
Admin
STS
API

I downloaded your repo yesterday, maybe in the appsettings is the mistake?

Thank you and Best Regards,
nk-cmd

**Comment by ViRuSTriNiTy** [comment]
Yes that`s true. The default configuration of each project needs manual tweeking before this works. For example, my configuration looks like

STS.Identity HTTPS 44300, HTTP 44200
Admin HTTPS 44301, HTTP 44201
Admin.Api HTTPS 44302, HTTP 44202

**Comment by skoruba** [comment]
It looks like that there is a colision in ports for Kestrel configuration, I will check it and fix it.
Sorry for that I use IIS Express by default. ;-)

STS starts for HTTPS on 5001 same like API on this port for HTTP. 
For now you can fix it manually in `launchSettings.json` - in STS project, remove https://localhost:5001 and keep only http://localhost:5000.

Or like @ViRuSTriNiTy suggested use your own configuration, but you need change all urls for IS4 clients.

BTW: I need these all ports reconfigure because issue: #550.

**Comment by skoruba** [comment]
Fixed in master, thanks for reporting.
