### ISSUE TITLE
 Problem to publish the STS project on production environment

### ISSUE THREAD

**Issue by poison2k** [skoruba/IdentityServer4.Admin#741]
Hello, 

i have a problem to publish the STS Project on production environment and i hope someone can help me.

Short problem description:
I published the STS on the IIS and get an error 500 but i can't find  further information in the EventLogs.  

What i have done:
- With Visual Studio i can start the local app without any trouble 
- It works on local DB and Production DB on the SQL-Server.
- I changed the localhost adress on launchsettings.json to production adress like: "https://mywebadress.com/"
- and changed sslPort to: 443
- now i published the STS with TaregtFramework 3.1, Target runtime "portable" , configuration "release"  and Deployment-Mode Framework depend
- on IIS Server i installed the current .NET Core Hosting Paket 
- creating an application Pool 
- create new site with binding on  "https://mywebadress.com/" port 443 with valid SSL certificate 
- start The app
    
Now i get Error 500 when i try to open the app on webbrowser. SSL Connection is Valid. 
When i start the application from console with "dotnet" command the appliocation starts in console and i get no errors.

I hope anybody has an idea or can say me what i have forgotten.  

Systeminformation:
- Windows Server 2012 R2
- IIS 8.5
- MS-SQL Server 2014

**Comment by vpetkovic** [comment]
I had no problems in IIS10. 
Since you haven't mentioned - I want to start with a question regarding pools. Under what pool are you trying to run it? It has to be individual app pool. See example. I have app pool for each: admin-api, admin, identity 

![image](https://user-images.githubusercontent.com/2244412/97472665-735c2a80-1920-11eb-9074-dd1c76268c6c.png)
